/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as StartRouteImport } from './routes/start'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppHubsRouteImport } from './routes/app.hubs'
import { Route as AppIntelligenceRouteImport } from './routes/app.intelligence'
import { Route as AppLearningRouteImport } from './routes/app.learning'
import { Route as AppNetworkRouteImport } from './routes/app.network'
import { Route as AppOpportunitiesRouteImport } from './routes/app.opportunities'
import { Route as AppPassportRouteImport } from './routes/app.passport'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppTutorRouteImport } from './routes/app.tutor'
import { Route as AppPeopleIdRouteImport } from './routes/app.people.$id'
import { Route as AppSimulationsIndexRouteImport } from './routes/app.simulations.index'
import { Route as AppSimulationsIdRouteImport } from './routes/app.simulations.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppHubsRoute = AppHubsRouteImport.update({
  id: '/hubs',
  path: '/hubs',
  getParentRoute: () => AppRoute,
} as any)
const AppIntelligenceRoute = AppIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppLearningRoute = AppLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppPassportRoute = AppPassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorRoute = AppTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleIdRoute = AppPeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulationsIndexRoute = AppSimulationsIndexRouteImport.update({
  id: '/simulations/',
  path: '/simulations/',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulationsIdRoute = AppSimulationsIdRouteImport.update({
  id: '/simulations/$id',
  path: '/simulations/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/start': typeof StartRoute
  '/api/chat': typeof ApiChatRoute
  '/app/help': typeof AppHelpRoute
  '/app/hubs': typeof AppHubsRoute
  '/app/intelligence': typeof AppIntelligenceRoute
  '/app/learning': typeof AppLearningRoute
  '/app/network': typeof AppNetworkRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/passport': typeof AppPassportRoute
  '/app/profile': typeof AppProfileRoute
  '/app/tutor': typeof AppTutorRoute
  '/app/': typeof AppIndexRoute
  '/app/people/$id': typeof AppPeopleIdRoute
  '/app/simulations/$id': typeof AppSimulationsIdRoute
  '/app/simulations/': typeof AppSimulationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/start': typeof StartRoute
  '/api/chat': typeof ApiChatRoute
  '/app/help': typeof AppHelpRoute
  '/app/hubs': typeof AppHubsRoute
  '/app/intelligence': typeof AppIntelligenceRoute
  '/app/learning': typeof AppLearningRoute
  '/app/network': typeof AppNetworkRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/passport': typeof AppPassportRoute
  '/app/profile': typeof AppProfileRoute
  '/app/tutor': typeof AppTutorRoute
  '/app': typeof AppIndexRoute
  '/app/people/$id': typeof AppPeopleIdRoute
  '/app/simulations/$id': typeof AppSimulationsIdRoute
  '/app/simulations': typeof AppSimulationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/start': typeof StartRoute
  '/api/chat': typeof ApiChatRoute
  '/app/help': typeof AppHelpRoute
  '/app/hubs': typeof AppHubsRoute
  '/app/intelligence': typeof AppIntelligenceRoute
  '/app/learning': typeof AppLearningRoute
  '/app/network': typeof AppNetworkRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/passport': typeof AppPassportRoute
  '/app/profile': typeof AppProfileRoute
  '/app/tutor': typeof AppTutorRoute
  '/app/': typeof AppIndexRoute
  '/app/people/$id': typeof AppPeopleIdRoute
  '/app/simulations/$id': typeof AppSimulationsIdRoute
  '/app/simulations/': typeof AppSimulationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/start'
    | '/api/chat'
    | '/app/help'
    | '/app/hubs'
    | '/app/intelligence'
    | '/app/learning'
    | '/app/network'
    | '/app/opportunities'
    | '/app/passport'
    | '/app/profile'
    | '/app/tutor'
    | '/app/'
    | '/app/people/$id'
    | '/app/simulations/$id'
    | '/app/simulations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/start'
    | '/api/chat'
    | '/app/help'
    | '/app/hubs'
    | '/app/intelligence'
    | '/app/learning'
    | '/app/network'
    | '/app/opportunities'
    | '/app/passport'
    | '/app/profile'
    | '/app/tutor'
    | '/app'
    | '/app/people/$id'
    | '/app/simulations/$id'
    | '/app/simulations'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/start'
    | '/api/chat'
    | '/app/help'
    | '/app/hubs'
    | '/app/intelligence'
    | '/app/learning'
    | '/app/network'
    | '/app/opportunities'
    | '/app/passport'
    | '/app/profile'
    | '/app/tutor'
    | '/app/'
    | '/app/people/$id'
    | '/app/simulations/$id'
    | '/app/simulations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  StartRoute: typeof StartRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hubs': {
      id: '/app/hubs'
      path: '/hubs'
      fullPath: '/app/hubs'
      preLoaderRoute: typeof AppHubsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/intelligence': {
      id: '/app/intelligence'
      path: '/intelligence'
      fullPath: '/app/intelligence'
      preLoaderRoute: typeof AppIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/learning': {
      id: '/app/learning'
      path: '/learning'
      fullPath: '/app/learning'
      preLoaderRoute: typeof AppLearningRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/network': {
      id: '/app/network'
      path: '/network'
      fullPath: '/app/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/opportunities': {
      id: '/app/opportunities'
      path: '/opportunities'
      fullPath: '/app/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/passport': {
      id: '/app/passport'
      path: '/passport'
      fullPath: '/app/passport'
      preLoaderRoute: typeof AppPassportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tutor': {
      id: '/app/tutor'
      path: '/tutor'
      fullPath: '/app/tutor'
      preLoaderRoute: typeof AppTutorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/people/$id': {
      id: '/app/people/$id'
      path: '/people/$id'
      fullPath: '/app/people/$id'
      preLoaderRoute: typeof AppPeopleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulations/': {
      id: '/app/simulations/'
      path: '/simulations'
      fullPath: '/app/simulations/'
      preLoaderRoute: typeof AppSimulationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulations/$id': {
      id: '/app/simulations/$id'
      path: '/simulations/$id'
      fullPath: '/app/simulations/$id'
      preLoaderRoute: typeof AppSimulationsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHelpRoute: typeof AppHelpRoute
  AppHubsRoute: typeof AppHubsRoute
  AppIntelligenceRoute: typeof AppIntelligenceRoute
  AppLearningRoute: typeof AppLearningRoute
  AppNetworkRoute: typeof AppNetworkRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRoute
  AppPassportRoute: typeof AppPassportRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTutorRoute: typeof AppTutorRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPeopleIdRoute: typeof AppPeopleIdRoute
  AppSimulationsIdRoute: typeof AppSimulationsIdRoute
  AppSimulationsIndexRoute: typeof AppSimulationsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHelpRoute: AppHelpRoute,
  AppHubsRoute: AppHubsRoute,
  AppIntelligenceRoute: AppIntelligenceRoute,
  AppLearningRoute: AppLearningRoute,
  AppNetworkRoute: AppNetworkRoute,
  AppOpportunitiesRoute: AppOpportunitiesRoute,
  AppPassportRoute: AppPassportRoute,
  AppProfileRoute: AppProfileRoute,
  AppTutorRoute: AppTutorRoute,
  AppIndexRoute: AppIndexRoute,
  AppPeopleIdRoute: AppPeopleIdRoute,
  AppSimulationsIdRoute: AppSimulationsIdRoute,
  AppSimulationsIndexRoute: AppSimulationsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  StartRoute: StartRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
