/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as StartRouteImport } from './routes/start'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTutorRouteImport } from './routes/app.tutor'
import { Route as AppSimulationsIndexRouteImport } from './routes/app.simulations.index'
import { Route as AppSimulationsIdRouteImport } from './routes/app.simulations.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorRoute = AppTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulationsIndexRoute = AppSimulationsIndexRouteImport.update({
  id: '/simulations/',
  path: '/simulations/',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulationsIdRoute = AppSimulationsIdRouteImport.update({
  id: '/simulations/$id',
  path: '/simulations/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/start': typeof StartRoute
  '/app/tutor': typeof AppTutorRoute
  '/app/': typeof AppIndexRoute
  '/app/simulations/$id': typeof AppSimulationsIdRoute
  '/app/simulations/': typeof AppSimulationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/start': typeof StartRoute
  '/app/tutor': typeof AppTutorRoute
  '/app': typeof AppIndexRoute
  '/app/simulations/$id': typeof AppSimulationsIdRoute
  '/app/simulations': typeof AppSimulationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/start': typeof StartRoute
  '/app/tutor': typeof AppTutorRoute
  '/app/': typeof AppIndexRoute
  '/app/simulations/$id': typeof AppSimulationsIdRoute
  '/app/simulations/': typeof AppSimulationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/start'
    | '/app/tutor'
    | '/app/'
    | '/app/simulations/$id'
    | '/app/simulations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/start'
    | '/app/tutor'
    | '/app'
    | '/app/simulations/$id'
    | '/app/simulations'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/start'
    | '/app/tutor'
    | '/app/'
    | '/app/simulations/$id'
    | '/app/simulations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  StartRoute: typeof StartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tutor': {
      id: '/app/tutor'
      path: '/tutor'
      fullPath: '/app/tutor'
      preLoaderRoute: typeof AppTutorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulations/': {
      id: '/app/simulations/'
      path: '/simulations'
      fullPath: '/app/simulations/'
      preLoaderRoute: typeof AppSimulationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulations/$id': {
      id: '/app/simulations/$id'
      path: '/simulations/$id'
      fullPath: '/app/simulations/$id'
      preLoaderRoute: typeof AppSimulationsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppTutorRoute: typeof AppTutorRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSimulationsIdRoute: typeof AppSimulationsIdRoute
  AppSimulationsIndexRoute: typeof AppSimulationsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppTutorRoute: AppTutorRoute,
  AppIndexRoute: AppIndexRoute,
  AppSimulationsIdRoute: AppSimulationsIdRoute,
  AppSimulationsIndexRoute: AppSimulationsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  StartRoute: StartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
