/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as StartRouteImport } from './routes/start'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppHubsRouteImport } from './routes/app.hubs'
import { Route as AppIntelligenceRouteImport } from './routes/app.intelligence'
import { Route as AppLearningRouteImport } from './routes/app.learning'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppMyNetworkRouteImport } from './routes/app.my-network'
import { Route as AppNetworkRouteImport } from './routes/app.network'
import { Route as AppOpportunitiesRouteImport } from './routes/app.opportunities'
import { Route as AppPassportRouteImport } from './routes/app.passport'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppTutorRouteImport } from './routes/app.tutor'
import { Route as AppEventsIndexRouteImport } from './routes/app.events.index'
import { Route as AppEventsIdRouteImport } from './routes/app.events.$id'
import { Route as AppPeopleIdRouteImport } from './routes/app.people.$id'
import { Route as AppSimulationsIndexRouteImport } from './routes/app.simulations.index'
import { Route as AppSimulationsIdRouteImport } from './routes/app.simulations.$id'
import { Route as AppWsModuleIndexRouteImport } from './routes/app.ws.$module.index'
import { Route as AppWsModuleThreadIdRouteImport } from './routes/app.ws.$module.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppHubsRoute = AppHubsRouteImport.update({
  id: '/hubs',
  path: '/hubs',
  getParentRoute: () => AppRoute,
} as any)
const AppIntelligenceRoute = AppIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppLearningRoute = AppLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMyNetworkRoute = AppMyNetworkRouteImport.update({
  id: '/my-network',
  path: '/my-network',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppPassportRoute = AppPassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorRoute = AppTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIdRoute = AppEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleIdRoute = AppPeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulationsIndexRoute = AppSimulationsIndexRouteImport.update({
  id: '/simulations/',
  path: '/simulations/',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulationsIdRoute = AppSimulationsIdRouteImport.update({
  id: '/simulations/$id',
  path: '/simulations/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppWsModuleIndexRoute = AppWsModuleIndexRouteImport.update({
  id: '/ws/$module/',
  path: '/ws/$module/',
  getParentRoute: () => AppRoute,
} as any)
const AppWsModuleThreadIdRoute = AppWsModuleThreadIdRouteImport.update({
  id: '/ws/$module/$threadId',
  path: '/ws/$module/$threadId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/start': typeof StartRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/app/help': typeof AppHelpRoute
  '/app/hubs': typeof AppHubsRoute
  '/app/intelligence': typeof AppIntelligenceRoute
  '/app/learning': typeof AppLearningRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/my-network': typeof AppMyNetworkRoute
  '/app/network': typeof AppNetworkRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/passport': typeof AppPassportRoute
  '/app/profile': typeof AppProfileRoute
  '/app/tutor': typeof AppTutorRoute
  '/app/': typeof AppIndexRoute
  '/app/events/$id': typeof AppEventsIdRoute
  '/app/people/$id': typeof AppPeopleIdRoute
  '/app/simulations/$id': typeof AppSimulationsIdRoute
  '/app/events/': typeof AppEventsIndexRoute
  '/app/simulations/': typeof AppSimulationsIndexRoute
  '/app/ws/$module/$threadId': typeof AppWsModuleThreadIdRoute
  '/app/ws/$module/': typeof AppWsModuleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/start': typeof StartRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/app/help': typeof AppHelpRoute
  '/app/hubs': typeof AppHubsRoute
  '/app/intelligence': typeof AppIntelligenceRoute
  '/app/learning': typeof AppLearningRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/my-network': typeof AppMyNetworkRoute
  '/app/network': typeof AppNetworkRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/passport': typeof AppPassportRoute
  '/app/profile': typeof AppProfileRoute
  '/app/tutor': typeof AppTutorRoute
  '/app': typeof AppIndexRoute
  '/app/events/$id': typeof AppEventsIdRoute
  '/app/people/$id': typeof AppPeopleIdRoute
  '/app/simulations/$id': typeof AppSimulationsIdRoute
  '/app/events': typeof AppEventsIndexRoute
  '/app/simulations': typeof AppSimulationsIndexRoute
  '/app/ws/$module/$threadId': typeof AppWsModuleThreadIdRoute
  '/app/ws/$module': typeof AppWsModuleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/start': typeof StartRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/app/help': typeof AppHelpRoute
  '/app/hubs': typeof AppHubsRoute
  '/app/intelligence': typeof AppIntelligenceRoute
  '/app/learning': typeof AppLearningRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/my-network': typeof AppMyNetworkRoute
  '/app/network': typeof AppNetworkRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/passport': typeof AppPassportRoute
  '/app/profile': typeof AppProfileRoute
  '/app/tutor': typeof AppTutorRoute
  '/app/': typeof AppIndexRoute
  '/app/events/$id': typeof AppEventsIdRoute
  '/app/people/$id': typeof AppPeopleIdRoute
  '/app/simulations/$id': typeof AppSimulationsIdRoute
  '/app/events/': typeof AppEventsIndexRoute
  '/app/simulations/': typeof AppSimulationsIndexRoute
  '/app/ws/$module/$threadId': typeof AppWsModuleThreadIdRoute
  '/app/ws/$module/': typeof AppWsModuleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/start'
    | '/api/chat'
    | '/api/transcribe'
    | '/app/help'
    | '/app/hubs'
    | '/app/intelligence'
    | '/app/learning'
    | '/app/messages'
    | '/app/my-network'
    | '/app/network'
    | '/app/opportunities'
    | '/app/passport'
    | '/app/profile'
    | '/app/tutor'
    | '/app/'
    | '/app/events/$id'
    | '/app/people/$id'
    | '/app/simulations/$id'
    | '/app/events/'
    | '/app/simulations/'
    | '/app/ws/$module/$threadId'
    | '/app/ws/$module/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/start'
    | '/api/chat'
    | '/api/transcribe'
    | '/app/help'
    | '/app/hubs'
    | '/app/intelligence'
    | '/app/learning'
    | '/app/messages'
    | '/app/my-network'
    | '/app/network'
    | '/app/opportunities'
    | '/app/passport'
    | '/app/profile'
    | '/app/tutor'
    | '/app'
    | '/app/events/$id'
    | '/app/people/$id'
    | '/app/simulations/$id'
    | '/app/events'
    | '/app/simulations'
    | '/app/ws/$module/$threadId'
    | '/app/ws/$module'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/start'
    | '/api/chat'
    | '/api/transcribe'
    | '/app/help'
    | '/app/hubs'
    | '/app/intelligence'
    | '/app/learning'
    | '/app/messages'
    | '/app/my-network'
    | '/app/network'
    | '/app/opportunities'
    | '/app/passport'
    | '/app/profile'
    | '/app/tutor'
    | '/app/'
    | '/app/events/$id'
    | '/app/people/$id'
    | '/app/simulations/$id'
    | '/app/events/'
    | '/app/simulations/'
    | '/app/ws/$module/$threadId'
    | '/app/ws/$module/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  StartRoute: typeof StartRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hubs': {
      id: '/app/hubs'
      path: '/hubs'
      fullPath: '/app/hubs'
      preLoaderRoute: typeof AppHubsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/intelligence': {
      id: '/app/intelligence'
      path: '/intelligence'
      fullPath: '/app/intelligence'
      preLoaderRoute: typeof AppIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/learning': {
      id: '/app/learning'
      path: '/learning'
      fullPath: '/app/learning'
      preLoaderRoute: typeof AppLearningRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-network': {
      id: '/app/my-network'
      path: '/my-network'
      fullPath: '/app/my-network'
      preLoaderRoute: typeof AppMyNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/network': {
      id: '/app/network'
      path: '/network'
      fullPath: '/app/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/opportunities': {
      id: '/app/opportunities'
      path: '/opportunities'
      fullPath: '/app/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/passport': {
      id: '/app/passport'
      path: '/passport'
      fullPath: '/app/passport'
      preLoaderRoute: typeof AppPassportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tutor': {
      id: '/app/tutor'
      path: '/tutor'
      fullPath: '/app/tutor'
      preLoaderRoute: typeof AppTutorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events/': {
      id: '/app/events/'
      path: '/events'
      fullPath: '/app/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events/$id': {
      id: '/app/events/$id'
      path: '/events/$id'
      fullPath: '/app/events/$id'
      preLoaderRoute: typeof AppEventsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/people/$id': {
      id: '/app/people/$id'
      path: '/people/$id'
      fullPath: '/app/people/$id'
      preLoaderRoute: typeof AppPeopleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulations/': {
      id: '/app/simulations/'
      path: '/simulations'
      fullPath: '/app/simulations/'
      preLoaderRoute: typeof AppSimulationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulations/$id': {
      id: '/app/simulations/$id'
      path: '/simulations/$id'
      fullPath: '/app/simulations/$id'
      preLoaderRoute: typeof AppSimulationsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ws/$module/': {
      id: '/app/ws/$module/'
      path: '/ws/$module'
      fullPath: '/app/ws/$module/'
      preLoaderRoute: typeof AppWsModuleIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ws/$module/$threadId': {
      id: '/app/ws/$module/$threadId'
      path: '/ws/$module/$threadId'
      fullPath: '/app/ws/$module/$threadId'
      preLoaderRoute: typeof AppWsModuleThreadIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHelpRoute: typeof AppHelpRoute
  AppHubsRoute: typeof AppHubsRoute
  AppIntelligenceRoute: typeof AppIntelligenceRoute
  AppLearningRoute: typeof AppLearningRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppMyNetworkRoute: typeof AppMyNetworkRoute
  AppNetworkRoute: typeof AppNetworkRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRoute
  AppPassportRoute: typeof AppPassportRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTutorRoute: typeof AppTutorRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEventsIdRoute: typeof AppEventsIdRoute
  AppPeopleIdRoute: typeof AppPeopleIdRoute
  AppSimulationsIdRoute: typeof AppSimulationsIdRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppSimulationsIndexRoute: typeof AppSimulationsIndexRoute
  AppWsModuleThreadIdRoute: typeof AppWsModuleThreadIdRoute
  AppWsModuleIndexRoute: typeof AppWsModuleIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHelpRoute: AppHelpRoute,
  AppHubsRoute: AppHubsRoute,
  AppIntelligenceRoute: AppIntelligenceRoute,
  AppLearningRoute: AppLearningRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppMyNetworkRoute: AppMyNetworkRoute,
  AppNetworkRoute: AppNetworkRoute,
  AppOpportunitiesRoute: AppOpportunitiesRoute,
  AppPassportRoute: AppPassportRoute,
  AppProfileRoute: AppProfileRoute,
  AppTutorRoute: AppTutorRoute,
  AppIndexRoute: AppIndexRoute,
  AppEventsIdRoute: AppEventsIdRoute,
  AppPeopleIdRoute: AppPeopleIdRoute,
  AppSimulationsIdRoute: AppSimulationsIdRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppSimulationsIndexRoute: AppSimulationsIndexRoute,
  AppWsModuleThreadIdRoute: AppWsModuleThreadIdRoute,
  AppWsModuleIndexRoute: AppWsModuleIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  StartRoute: StartRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
